//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeSub
    {
        public int GradeSubID { get; set; }
        public int SubjectsID { get; set; }
        public int GradeID { get; set; }
        public int EmployeeID { get; set; }
    
        public virtual Grade Grade { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
