//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SecurityEntities : DbContext
    {
        public SecurityEntities()
            : base("name=SecurityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tAccessRole> tAccessRoles { get; set; }
        public virtual DbSet<tAccessRoleDet> tAccessRoleDets { get; set; }
        public virtual DbSet<tEmployee> tEmployees { get; set; }
        public virtual DbSet<tModule> tModules { get; set; }
        public virtual DbSet<tUser> tUsers { get; set; }
        public virtual DbSet<tUserAccessRole> tUserAccessRoles { get; set; }
    }
}
