//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccessRole
    {
        public int UserAccessRoleID { get; set; }
        public int UserID { get; set; }
        public int AccessRoleID { get; set; }
    
        public virtual AccessRole AccessRole { get; set; }
        public virtual User User { get; set; }
    }
}
